picklistsrus/objects/ReusablePicklistOption__mdt.object
<CustomObject>
    <fields>
        <fullName>Picklist__c</fullName>
        <label>Picklist</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reusable Picklist Option</label>
    <pluralLabel>Reusable Picklist Options</pluralLabel>
</CustomObject>

picklistsrus/classes/BLDR_OptionRenameTest.cls
@IsTest
public class BLDR_OptionRenameTest {
    static BLDR_MetadataServiceMock mock {get; set;}
    
    public static testmethod void testSave() {
        BLDR_OptionRenameController ctrlr = setup();
        ctrlr.option.recordLabel = 'The best option!';
        ctrlr.save();
        System.assert(mock.didUpdate);
    }

    static BLDR_OptionRenameController setup() {
        mock = new BLDR_MetadataServiceMock();
        Test.setMock(WebServiceMock.class, mock);
        PageReference optionRename = Page.BLDR_OptionRename;
        optionRename.getParameters().put('picklistApiName', 
                                         ReusablePicklistTestUtil.getDevNamespaceWithSep() + 'TestPicklistNonAlpha');
        optionRename.getParameters().put('id',
                                        [SELECT Id from ReusablePicklistOption__mdt
                                         WHERE Picklist__c = 'TestPicklistNonAlpha'][0].Id);
        Test.setCurrentPage(optionRename);
        return new BLDR_OptionRenameController();
    }
}